
[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[dev]
  command = "npm run dev"
  port = 8888
  targetPort = 8080
  publish = "dist"
  framework = "#custom"
  autoLaunch = false

# Redirect all API requests to Netlify Functions
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Fallback for all other routes to the SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
